<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GymOS.Application\GymOS.Application.csproj" />
    <ProjectReference Include="..\GymOS.Domain\GymOS.Domain.csproj" />
    <ProjectReference Include="..\GymOS.Shared\GymOS.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.101.6" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.1" />
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24" />
    <PackageReference Include="Hangfire.Core" Version="1.8.24" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Otp.NET" Version="1.4.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
